name: fwup
version: '1.2.5'
summary: Configurable embedded Linux firmware update creator and runner
description: |
  fwup lets you create and apply firmware updates for embedded Linux-based
  systems. It supports several power failure safe update strategies and has
  a simple and constrained update language. It has been ported to many
  many platforms so non-Linux users can also create SDCards or raw image
  files for devices.

grade: stable
confinement: strict

apps:
    fwup:
        command: fwup
        plugs:
            - removable-media
            - mount-observe

parts:
    fwup:
        plugin: autotools
        source: https://github.com/fhunleth/fwup/releases/download/v1.2.5/fwup-1.2.5.tar.gz

        # Build a static version of fwup to avoid incompatible libconfuse versions
        override-build: |
            ./scripts/download_deps.sh
            ./scripts/build_deps.sh
            PKG_CONFIG_PATH=$PWD/build/host/deps/usr/lib/pkgconfig ./configure \
                --enable-shared=no \
                --prefix=$SNAPCRAFT_PART_INSTALL/usr
            make -j $(getconf _NPROCESSORS_ONLN)
            make install
        build-packages:
            - curl
            - pkg-config
            - help2man

